#!/usr/bin/env sh
#-------------------------------------------------------------- history file --#
HISTFILE=$HOME/.history
HISTFILESIZE=151000
#----------------------------------------------------- history file max size --#
HISTSIZE=151000
#----------------------------------- max number of lines to write to history --#
SAVEHIST=150000
#---------------------------------------------------------- history settings --#
HISTTIMEFORMAT="%FT%T %Z"
HISTCONTROL=ignoreboth # ignorespace and ignoredups
HISTIGNORE="ls:ll:lsl:cd:pwd:history"

#---------------------------------------------------------------- HOME LOCAL --#
export PATH="$HOME/bin:$PATH"

#-------------------------------------------------------- APP SPECIFIC PATHS --#
# export PATH="$HOME/.composer/vendor/bin:$PATH"

#-------------------------------------------------------------------- GO ENV --#
# https://pkg.go.dev/cmd/go#hdr-Environment_variables
# export GO111MODULE=on                   # should be auto or undefined
export GOROOT="/usr/local/go"             # this is the default location; ONLY used for custom install location
export GOPATH="$HOME/go"                  # points to local workspace... this is necessary for legacy go code that isn't using modules
export GOBIN="$GOPATH/bin"                # destination for bins after `go install`
export PATH="$GOBIN:$PATH"                # adding $GOBIN to the path to use installed bins
export PATH="$GOROOT/bin:$PATH"           # adding $GOROOT to the path to use installed bins
export GOPROXY=direct                     # https://proxy.golang.org
export GOSUMDB=off
export GOPRIVATE=
# export GOROOT_FINAL="/usr/local/go"      # destination after building from source
# export GOROOT_BOOTSTRAP=$GOROOT          # to build new versions of Go, point to the 1.4 bootstrap version of Go
# export GOVCS=public:git|hg,private:all   # this is default

#---------------------------------------------------------------------- BREW --#
# export PATH="$PATH:/usr/local/Homebrew/bin"  # apple intel
export PATH="$PATH:/opt/homebrew/bin"              # apple silicon
export PATH="$PATH:/home/linuxbrew/.linuxbrew/bin" # ubuntu
export HOMEBREW_NO_AUTO_UPDATE=1

#-------------------------------------------------------------------- VSCode --#
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin" #default

#-------------------------------------------------------------- Sublime Text --#
export PATH="$PATH:/Applications/Sublime Text.app/Contents/SharedSupport/bin"

#-------------------------------------------------------------- cleanup path --#
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:/usr/local/sbin"
export PATH="$PATH:$HOME/dotfiles/bin"

#------------------------------------------------- Alias [`man zshbuiltins`] --#
# $ man ls # will describe how to customize ls colors
alias lsl='ls -AFGTlh '  # --time-style=+'%b %e %T %Y' ## MacOS, BSD
# alias lsl='ls -AFClh --color ' # --time-style=+'%b %e %T %Y' ## Linux
alias less='less -S '
alias ed='ed -p:'
alias h='history -25'
alias hall='history 1'
alias psp='ps -eo user,group,pid,comm,args'
alias psa='ps aux'
alias grep='grep --color '
alias gome='cd "$HOME/code/go/src" '
alias topen='open -a Terminal '
alias diff='diff -u --color=always '

#------------------------------------------------------- these are important --#
#--------------------------- these are off as they mess with tmux and screen --#
export EDITOR="ed -p:"
export CLICOLOR_FORCE=true
export VISUAL="$EDITOR"
export PAGER=cat
export DIFFCOLORS="31:32" # ascii color codes ... add:rm
export GLAMOUR_STYLE="$HOME/dotfiles/conf/gh/monokai22.json" # set gh color scheme

#--------------------------------------------------------------------- SNIPS --#
alias snips="cat \"$HOME\"/dotfiles/resources/snips/* "
for f in "$HOME"/dotfiles/resources/snips/*; do
	F=$(basename -s .txt "$f")
	alias "$F"="echo \"\n\" && cat \"$f\" && echo \"\n\" "
done

# output a given snip file path/name to open in an editor
snip_file () {
	f="$HOME/dotfiles/resources/snips/snips_$1.txt"
	if [ -f "$f" ]; then
		echo "$f"
	fi
}

#--------------------------------------------------------------------- ASCII --#
export ASCII_FILE="$HOME/dotfiles/resources/terminal/ascii.tsv"
alias ascii="head -133 \"$ASCII_FILE\" "
alias asciix="cat \"$ASCII_FILE\" "

#----------------------------------------------------------------------- IRC --#
export IRCNAME=henderjon
export IRCNICK=henderjon
export IRCUSER=henderjon

#---------------------------------------- reload env file when we reload zsh --#
if [ -f "$HOME/.zshenv" ]; then
	source "$HOME/.zshenv"
fi

#---------------------------------------- reload env file when we reload zsh --#
if [ -n "$ZSH_VERSION" ]; then
   _LOCAL_ENV_TYPE="zsh"
elif [ -n "$BASH_VERSION" ]; then
   _LOCAL_ENV_TYPE="bash"
fi

#-------------------------------------------- name the ENV based on env file --#
if [ -z "$_LOCAL_ENV_NAME" ]; then
	_LOCAL_ENV_NAME="henderjon"
fi

#------------------------------------------------------ label screened terms --#
if [[ "$TERM" = "screen"* ]] && [ -z "$TMUX" ]; then
	XTERM=" (screen)"
elif [[ "$TERM" = "screen"* ]] && [ -n "$TMUX" ]; then
	XTERM=" (tmux)"
else
	XTERM=""
fi

if [[ "$OSTYPE" == darwin* ]]; then
	alias iclouddrive='cd "$HOME/Library/Mobile\ Documents/com~apple~CloudDocs" '
	alias python='python3 '
fi
