#!/usr/bin/env sh

_has_changed(){
	if ! cmp -s "$1" "$2"; then
		echo "diff; $1 has been changed"
		exit 1
	else
		echo "same; $1 has not been changed"
	fi
}

echo "did you run update.sh? [y/n] "
read -r CONFIRM < /dev/tty
if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "yes" ]; then
	exit 1
fi

# -----
_has_changed "conf/nginx/conf/fastcgi_params" "$HOME/code/conf/nginx/conf/fastcgi_params"
_has_changed "conf/nginx/conf/nginx.conf" "$HOME/code/conf/nginx/conf/nginx.conf"
# -----
_has_changed "conf/php/php-fpm.conf" "$HOME/code/conf/php/7.4 macOS build/php-fpm.conf"
_has_changed "conf/php/php.ini" "$HOME/code/conf/php/7.4 macOS build/php.ini"
# -----
_has_changed "resources/terminal/pre-commit" ".git/hooks/pre-commit"
