cask 'font-amazon-ember' do
  version "1.010"
  sha256 "7d41839edb43b49acb8409604f88c26f3e1b7c642fb712ff04ec62c951e88cd9"

  url "https://m.media-amazon.com/images/G/01/mobile-apps/dex/alexa/branding/Amazon_Typefaces_Complete_Font_Set_Mar2020.zip"
  name "Amazon Ember & Bookerly"
  homepage "https://developer.amazon.com/en-US/alexa/branding/echo-guidelines/identity-guidelines/typography"

  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly Display/BookerlyDisplay_Bd.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly Display/BookerlyDisplay_BdIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly Display/BookerlyDisplay_It.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly Display/BookerlyDisplay_Rg.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/Bookerly-Bold.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/Bookerly-BoldItalic.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/Bookerly-Italic.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/Bookerly-Regular.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/BookerlyLCD_Bd.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/BookerlyLCD_BdIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/BookerlyLCD_It.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Bookerly/BookerlyLCD_Rg.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_Bd.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_BdIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_Lt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_LtIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_Rg.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_RgIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_Th.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Condensed/AmazonEmberCdRC_ThIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Display/AmazonEmberDisplay_Bd.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Display/AmazonEmberDisplay_He.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Display/AmazonEmberDisplay_Lt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Display/AmazonEmberDisplay_Md.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember Display/AmazonEmberDisplay_Rg.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/Amazon-Ember-Medium.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/Amazon-Ember-MediumItalic.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_Bd.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_BdIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_He.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_HeIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_Lt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_LtIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_Rg.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_RgIt.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_Th.ttf"
  font "Amazon_Typefaces_Complete_Font_Set_Mar2020/Ember/AmazonEmber_ThIt.ttf"
end
